# Generated by Django 3.0 on 2020-03-06 01:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('save', '0002_auto_20200306_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='date_added',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
