# Generated by Django 3.0 on 2020-03-05 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentModel',
        ),
    ]
