# Generated by Django 3.0 on 2020-03-10 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citymodel',
            options={'verbose_name_plural': 'cities'},
        ),
    ]
